<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions targetNamespace="http://server.soap.zvezdochet.kz/" name="CalculatorService" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:tns="http://server.soap.zvezdochet.kz/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
  <types>
    <xsd:schema>
      <xsd:import namespace="planet" schemaLocation="CalculatorService_schema1.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://server.soap.zvezdochet.kz/" schemaLocation="CalculatorService_schema2.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="house" schemaLocation="CalculatorService_schema3.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="configuration" schemaLocation="CalculatorService_schema4.xsd"/>
    </xsd:schema>
  </types>
  <message name="calculate">
    <part name="parameters" element="tns:calculate"/>
  </message>
  <message name="calculateResponse">
    <part name="parameters" element="tns:calculateResponse"/>
  </message>
  <portType name="Calculator">
    <operation name="calculate">
      <input wsam:Action="http://server.soap.zvezdochet.kz/Calculator/calculateRequest" message="tns:calculate"/>
      <output wsam:Action="http://server.soap.zvezdochet.kz/Calculator/calculateResponse" message="tns:calculateResponse"/>
    </operation>
  </portType>
  <binding name="CalculatorPortBinding" type="tns:Calculator">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="calculate">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CalculatorService">
    <port name="CalculatorPort" binding="tns:CalculatorPortBinding">
      <soap:address location="http://zvezdochetkz.appspot.com/calc"/>
    </port>
  </service>
</definitions>

